[build-system]
requires = ["setuptools>=80"]
build-backend = "setuptools.build_meta"

[project]
name = "trex-gym"
version = "0.1.0"
description = "Tyrannosaur model tooling."
readme = "README.md"
requires-python = ">=3.12,<3.13"
license = "MIT"
authors = [
    { name = "Jeffrey T. Bingham", email = "bingjeff@gmail.com" },
]
dependencies = [
    "jax<0.10",
    "jaxlib<0.10",
    "mujoco",
    "mujoco-mjx>=3.8.0",
    "numpy",
    "playground[learning]>=0.2.0",
    "pycollada",
    "scipy",
    "warp-lang==1.12.0",
]

[dependency-groups]
dev = [
    "black",
]
gpu = [
    "jax[cuda12]<0.10",
]

[tool.setuptools.packages.find]
include = ["mjx_gym*", "old*"]

[tool.black]
line-length = 88
target-version = ["py312"]
